#include <unistd.h>
#include<stdio.h>

int main() 
{
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\nengine starting");
    sleep(2);
    printf("\nready to launch");
    sleep(1);
    printf("\n3");
    sleep(2);
    printf("\n2");
    sleep(2);
    printf("\n1");
    sleep(2);
    printf("\ngooooo");
    sleep(2);
    printf("\n                   /\\           ");
    printf("\n                  /  \\          ");
    printf("\n                 /    \\          ");
    printf("\n                /      \\          ");
    printf("\n               /        \\          ");
    printf("\n              |    I     |           ");
    printf("\n              |    S     |           ");
    printf("\n              |    R     |           ");
    printf("\n              |    O     |           ");
    printf("\n              |          |           ");
    printf("\n              |          |           ");
    printf("\n              |          |           ");
    printf("\n              |          |           ");
    printf("\n              |          |           ");
    printf("\n              |          |           ");
    printf("\n              |          |           ");
    printf("\n             ||          ||           ");
    printf("\n            //|          |\\           ");
    printf("\n           // |          | \\         ");
    printf("\n          //  |          |  \\         ");
    printf("\n         //   |          |   \\         ");
    printf("\n        //    |          |    \\         ");
    printf("\n       //     |          |     \\         ");
    printf("\n      //      |          |      \\         ");
    printf("\n     //       |          |       \\         ");
    printf("\n    ||        |          |        ||        ");
    printf("\n    ||        |          |        ||        ");
    printf("\n    ||        |          |        ||        ");
    printf("\n    ||        ------------        ||        ");
    printf("\n    ||        | |      | |        ||         ");
    printf("\n   /  \\       / \\      / \\       /  \\         ");
    printf("\n             ^^^^^    ^^^^^                    ");
    printf("\n           ^^^^^^^^^ ^^^^^^^^^                    ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
    printf("\n  ");
    sleep(1);
}        
